[package]
name = "debug_system"
version = "0.1.0"
authors = ["Kaneyuki Hiromasa <matsugen2511@gmail.com>"]
edition = "2018"

[dependencies]
amethyst={git="https://github.com/amethyst/amethyst.git"}
log= "0.4.8"
serde= "1.0.105"
